### PR TITLE
Fixed the error on invalid prompt

### LINKED ISSUE #364: node.js simply not working, at all
No matter what I try, after 4 hours I can't get around this one. I've changed the paths and more.

net.js:605
    throw new TypeError('invalid data');

TypeError: invalid data
    at Socket.write (net.js:605:11)
    at REPLServer.Interface.prompt (readline.js:176:17)
    at REPLServer.displayPrompt (repl.js:397:8)
    at new REPLServer (repl.js:328:8)
    at Object.exports.start (repl.js:337:14)
    at C:\Users\MrRob\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:5:20
    at Object.<anonymous> (C:\Users\MrRob\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:38:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)

**_Repl Closed**_

```
```

### PR DESCRIPTION
**Pull request by prog-rajkamal**
This pull request closes #364.

### CODE REVIEW

**Comment by gacelita** [comment]
Sorry, pull requests need to go on branch "merges", which is the ugly solution we found for merging the outstanding amount of pending pull requests after a long period of lack of maintenance.

Please fix the conflicts and I'll merge it there.

**Comment by prog-rajkamal** [comment]
so, I fork from master branch and merge it to merges branch?

**Comment by gacelita** [comment]
I'd rather follow the command line instructions Github offers you inside the "This branch has conflicts that must be resolved" box.
That's the easiest, fastest path.

**Comment by prog-rajkamal** [comment]
Closing this PR. because #499  is already merged. I hope you push the changes to master and Package Control soon.

**Pull request closed without merging**
