### PR TITLE
Attempted fix for windows "handle is invalid" error. (Issue #271)

### PR DESCRIPTION
**Pull request by ehuss**
I don't know if this is wise, but this is the smallest patch I could make
that fixes the "handle is invalid" bug.  I do not fully understand why
the version of CreateProcessW in _winapi works and the one in winprocess
does not.  There have been a lot of changes to the Popen class, and the
version of _execute_child in SublimeREPL has diverged a bit from the one
in the subprocess module, so maybe there are some bad subtle assumptions.

This probably won't work in Sublime 2.  I could look into accomodating
that as well (probably just need to use _subprocess).  However, I'm not
sure this is really the best approach.

### CODE REVIEW

**Comment by gacelita** [comment]
I'm even less sure than you. Not going to merge for now.

**Comment by gacelita** [comment]
Could you test this and make sure that it solves the problem instead of making it worse? I'll merge it then

**Comment by ehuss** [comment]
I've been using this since I posted it without problems.  Do we want to continue supporting Sublime 2?  This patch probably doesn't work there.

**Comment by gacelita** [comment]
@wuub Do we want to continue supporting Sublime 2?

**Comment by wuub** [comment]
It's a difficult question which should probably be answered after asking @wbond for some stats on ST2/ST3 usage right now (preferably for users of SublimeREPL). 

There still might exist a quite large ST2 userbase, but I'm personally not against dropping support and freezing version for ST2.

**Comment by wbond** [comment]
From looking at recent Package Control statistics, ST2 users make up less than 10% of users, and the number keeps dropping. Jon and I are working towards a stable ST3 release, at which point I would expect most remaining users will upgrade.

**Comment by gacelita** [comment]
I vote for merging this and, after proper testing, releasing the "merges" branch as an ST3-only release.

**Comment by wuub** [comment]
Yup, IMO we should freeze ST2 branch immediately and focus on st3 only.

**Pull request merged**
